### ISSUE TITLE
VM Execution Aborted

### ISSUE THREAD

**Issue by TheoDrHashiriya** [cyberc001/DoomDynMus#1]
## Console Log
VM execution aborted: array access out of bounds. Size = 0, current index = 0
Called from DMus_Player.OnTick at
DoomDynMus-master.zip:zscript/musplayer.zc, line 144
Called from DMus_Handler.UiTick at
DoomDynMus-master.zip:zscript/mushandler.zc, line 55

## Sourceport Info
GZDoom v4.6.0 Windows 64bit

## Load Order
doom2.wad
DoomDynMus-master.zip
DMus_Payday.zip

## Reproduction
- Download [DMus_Payday.zip](https://github.com/cyberc001/DoomDynMus/files/6677430/DMus_Payday.zip).
- Launch load order.
- Get killed by enemies and press the Use button.
- Press Alt+F4 to exit application.

**Comment by TheoDrHashiriya** [comment]
[SOLVED]
Fix: Added new track group.

**Comment by TheoDrHashiriya** [comment]
- Problem still persists even after two track groups are present. 
### New Console Error Log
VM execution aborted: array access out of bounds. Size = 1, current index = 1
Called from DMus_Player.OnTick at
DoomDynMus-master.zip:zscript/musplayer.zc, line 144
Called from DMus_Handler.UiTick at
DoomDynMus-master.zip:zscript/mushandler.zc, line 55

**Comment by cyberc001** [comment]
Indeed, the bug was caused by tracks ending with an EOF not being parsed properly. Fixed in 5e11f70b6dc66b80b661187f3bb28af233d2e7e0 .

**Comment by TheoDrHashiriya** [comment]
Error still persists at times, especially during gameplay. However, it can now be exited by pressing the Escape button, unlike the previous mod version.
